import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientLayout from "@/components/ClientLayout";
import { Header } from "@/components/Header";
import { NavbarAside } from "@/components/NavbarAside";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Narugak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-white">
        <div className="relative w-full max-w-screen mx-auto ">
          <div className="grid h-full grid-cols-[80px_1fr] ">
            <Header />
            <NavbarAside />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
